### PR TITLE
#114 - this is a first attempt at getting the text or rich text value…

### PR DESCRIPTION
**Pull request by robertjf**
…s from a block list or grid for description meta fields

### CODE REVIEW

**Comment by patrickdemooij9** [comment]
Looking very good for a first version @robertjf!

Did find a small bug in that, if your value is coming from a TinyMCE, it will also take the HTML, but I am sure that can be solved. The only thing that I "worry" about is that the component does feel a bit like magic as you don't know what it does, but not quite sure how to solve that. 
Might just need to write some documentation, so that people can find what it currently does.

**Comment by robertjf** [comment]
yep - I'll get the HTML bit fixed up and push up a change.

And yes with the documentation.

**Comment by robertjf** [comment]
@patrickdemooij9 the HTML issue is resolved... where do you maintain the documentation for this?

**Comment by patrickdemooij9** [comment]
Perfect! The documentation is here: https://seotoolkit.gitbook.io/useotoolkit/. But don't worry, I'll make sure to write a bit about it!

**Comment by patrickdemooij9** [comment]
Great first version! Hopefully we can build upon it in future versions, but this will definitely help people out there.

**Pull request merged**
