### PR TITLE
Draft for syncing metafields with usync

### LINKED ISSUE #39: Connect with uSync
Would be great if we can connect all the extra document type settings to uSync so users can easily move them from environment to environment. Would probably be available in a separate project.

### PR DESCRIPTION
**Pull request by krebil**
Fixes [39](https://github.com/patrickdemooij9/SeoToolkit.Umbraco/issues/39)

The initial draft for uSync implementation. 

- [x] Sync meta field- / SEO field values
- [x]  Add reporting to meta fields
- [x]  Support language variants

- [ ] Sync SEO settings
- [ ] Add reporting to Seo settings

@patrickdemooij9 take a look and let me know if you want any changes, I'll look into synching the settings portion either later today or tomorrow morning.

Other Notes:

- I've used the [default content serializer](https://github.com/KevinJump/uSync/blob/ed629c5dffe42b029852d027abbf56d2115d0b87/uSync.Core/Serialization/Serializers/ContentSerializer.cs) as the basis
- Maybe there should also be some logic in place to detect whether the open graph image exists on import

### CODE REVIEW

**Comment by patrickdemooij9** [comment]
@krebil absolutely amazing! Export and import work great!

There is one issue that I can see with the report function:
image

I've tried to fix it, but I can't quite figure out where it is going wrong. I think the error is thrown here (https://github.com/KevinJump/uSync/blob/ab2f1f0e26683da6c8c600fd8de5dc9acf94af44/uSync.Core/Serialization/SyncSerializerRoot.cs#L246), but we override that code (I also tried overriding the one with 3 parameters), but it doesn't get hit when reporting... Almost like that serializer isn't being called on report.

Also noticed an error on startup, so I quickly fixed that.

But amazing work so far!

**Comment by krebil** [comment]
Ah yes I haven't done anything with reporting yet. It probably needs an override in the handler file. I'll look into it in the morning :)

**Comment by krebil** [comment]
@patrickdemooij9 
I've added language variants and reporting both seem to work alright. 
Next up is the whole settings section

**Comment by patrickdemooij9** [comment]
Hi @krebil 
Have you already started on the settings section? Otherwise I might be able to help out with that this weekend

**Comment by krebil** [comment]
@patrickdemooij9 Sounds great, I have been really busy with work. So I've only looked at it briefly. Usync is structured towards saving Tree items. So I don't know what the right structure would be. For the values section I've piggy backed unto the content items themselves. And something similar could be done with the document types.

Let me know if you need anything. I'll be working this weekend. But I'll be available

**Comment by krebil** [comment]
I've been looking on and off for a while. I can't find much reference to pulling data outside of a tree with USync and everything I've come up with so far feels hacky.  

Umbraco deploy seems easier though. So maybe I'll give that a shot and see if that implementation gives some more insight into this

**Comment by ianleeder** [comment]
Any progress on this?

I'd also be interested to know if it would work for uSync (Complete) Publisher - direct sync server-server.

**Comment by krebil** [comment]
I got pointed in another direction by Kevin, https://github.com/KevinJump/uSync/issues/479
I'll try this out sometime this week

**Comment by krebil** [comment]
I'm about halfway done with this, and should be done at the end of the week. This approach seems much cleaner. I'll move to a new pull request targeting v11

@patrickdemooij9 would you be up for reviewing?

**Comment by patrickdemooij9** [comment]
Yeah, I'll take a look at what you have tonight and then give it another look when it's done!

**Comment by krebil** [comment]
I've moved to another pull request https://github.com/patrickdemooij9/SeoToolkit.Umbraco/pull/175
@patrickdemooij9

**Pull request closed without merging**
