### PR TITLE
📦 Updates to support Umbraco 13

### PR DESCRIPTION
**Pull request by robertjf**
This commit upgrades the projects to support Umbraco 13, and upgrades the test website to Umbraco 13.0.3 with Clean theme 4.0.0

### CODE REVIEW

**Comment by christerj** [comment]
This is great, we need this like yesterday but I think we have to wait for when it's published on nuget. So please hurry with that :)

**Comment by patrickdemooij9** [comment]
Hi @robertjf
Sorry for the late reply. Last couple of weeks have been something. I'll try to take a look at this today and compare it with the other PR that is currently open and hopefully merge one of the two back (they are both upgrades to v13)

Thank you so much for the PR though! Really appreciate it.

**Comment by patrickdemooij9** [comment]
I just made sure that the targetframework for all the packages was set to .NET8.0 (Same as Umbraco13). All the other logic still seems to work as expected so I'll merge this one back.
Thank you again for the PR! I'll be releasing a new package in the coming days

**Comment by robertjf** [comment]
Yep, the only reason I didn't update the TargetFramework was to allow earlier versions of Umbraco to work with the package without having to move to dotnet 8.

**Comment by patrickdemooij9** [comment]
> Yep, the only reason I didn't update the TargetFramework was to allow earlier versions of Umbraco to work with the package without having to move to dotnet 8.

Good point, I've just pushed a commit to allow dotnet 7 & 8: https://github.com/patrickdemooij9/SeoToolkit.Umbraco/commit/820e7aea1b51ee77b7bc131e05cf3c2f3da51f40

**Pull request merged**
