### PR TITLE
Twitter Metadata field support

### PR DESCRIPTION
**Pull request by robertjf**
This PR Addresses #191 by adding additional Metadata Fields.  The Card type can be selected by dropdown.

### CODE REVIEW

**Comment by patrickdemooij9** [comment]
Looks great! I'll take a better look & test it in the following days and let you know if I have any feedback. But really appreciate this PR and the other one that you did!

**Comment by robertjf** [comment]
Thanks @patrickdemooij9  - let me know if I can be of assistance; really itching to get this released so we can use it on a couple of projects :)

**Comment by patrickdemooij9** [comment]
Hi @robertjf 
Great PR! Just spotted a few small things. If you want, I can also pick these up but I'll let that decision up to you. Really appreciate the work you do here!

**Comment by robertjf** [comment]
hey @patrickdemooij9 let me know what they are, and I'll jump on them straight away :)

**Comment by patrickdemooij9** [comment]
> hey @patrickdemooij9 let me know what they are, and I'll jump on them straight away :)

You should be able to see them above our messages :)

**Comment by robertjf** [comment]
hm.  Not seeing them at all..

**Comment by robertjf** [comment]
@patrickdemooij9 are they marked as private by any chance?

**Comment by patrickdemooij9** [comment]
Hmm, I don't see anything related to private in the mobile app. I'll take a look at it tomorrow in the browser. The feedback was:

- I think the open graph URL should probably belong in the open graph group.
- Let's put all the Twitter related meta fields in their own group between open graph and extra information.
- Are you sure that product is a valid Twitter card type? I didn't see it listed in their documentation.
- The Twitter card type dropdown should probably have an empty option. Currently, there is no way to "empty" your field and use the fallback value.

Hopefully I'll be able to get review points showing for you tomorrow.

**Comment by robertjf** [comment]
great - I'll get to work on those in the meantime.

**Comment by robertjf** [comment]
@patrickdemooij9 I'm about to push up some changes for you - I'm not 100% convinced that the twitter specific fields should be in their own group though; the twitter preview widget is still in the Open Graph group so it's a little disjointed.

Still, I do like the separation.  For Facebook I've also added  [facebook app_id](https://developers.facebook.com/docs/sharing/webmasters) field as well, also in it's own group.

Perhaps we should call the group "Social Media" instead of "Open Graph" and keep it all together?

image

**Comment by patrickdemooij9** [comment]
@robertjf You're right, the preview doesn't really fit then. I think a Social Media Group would be a great idea to do then!

**Comment by robertjf** [comment]
ok, so if we rename the group from Open Graph to Social Media, would that work?  and consolidate the fields into that?

**Comment by patrickdemooij9** [comment]
Yes, I think that is the way to go about it

**Comment by robertjf** [comment]
all done :)

**Comment by patrickdemooij9** [comment]
PR looks great! I've merged it and I will try to release it somewhere next week. Trying to get a few more changes added for the next version

**Pull request merged**
